package useCases

func handle(err error) {
	trackError(err)
}
